### ISSUE TITLE
Provide a community EE image

### ISSUE THREAD

**Issue by Andersson007** [ansible-community/community-team#301]
#### Provide a community-ee EE image.

- `base_image`: fedora-minimal

- `ansible-core`: It'll contain the latest ansible-core version included in the package

- `collections`: it'll contain the following set of collections, versions included in the package:
  - ansible.netcommon
  - ansible.posix
  - ansible.utils
  - ansible.windows

- `release schedule`: It should be integrated in Ansible package release process: built and published in the same day or shortly after a package release

- `EE tag versioning`: Versioning would be the core tag + a patch number, e.g
  - EE with core `2.15.2` comes out -> `community-ee:2.15.2-1`
  - EE with core `2.15.3` comes out -> `community-ee:2.15.3-1`, etc.

- `package location`: the EE image should be published under https://github.com/orgs/ansible/packages

- `testing`: No testing for now. "its mostly best effort, so as long as an hello world echo works we are good."

#### Building the image

The image can be built using the following commands:

1. `sudo dnf install -y podman python3`
2. `pip3 install ansible-builder`
3. `mkdir community_ee && cd community_ee`
4.  Create a `execution-environment.yml` file that specifies dependencies to include in the image, sample:
```
cat > execution-environment.yml<<EOF
---
version: 3
images:
  base_image:
    name: quay.io/fedora/fedora:latest
dependencies:
  ansible_core:
    package_pip: ansible-core==2.15.1
  ansible_runner:
    package_pip: ansible-runner
  galaxy:
    collections:
    - name: ansible.netcommon
      version: 5.1.0
    - name: ansible.posix
      version: 1.5.0
    - name: ansible.utils
      version: 2.10.0
    - name: ansible.windows
      version: 1.14.0
EOF
```
5. `ansible-builder build --tag community-ee:<tag>`
